Muscular Eggshell Pike

Medium

# Allowance not reverted on failure leads to DoS in `supply`, `repay`, and `liquidation` functions

### Summary

In the `CoreRouter`, the `_approveToken` function is called during `supply` and `repayBorrowInternal` to set the allowance for the `LToken` contract. If a revert occurs after _approveToken (for example, during a failed mint, repay, or transfer), the increased allowance remains set. This can lead to a denial-of-service (DoS) condition: subsequent calls to supply, repay, or liquidation functions will revert if the allowance is already set to a value lower than the new `_amount`, due to the `safeApprove` pattern requiring the allowance to be zero before increasing it.

### Root Cause

- [supply -- line 71](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CoreRouter.sol#L71)
- [repayBorrowInternal -- line 485](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CoreRouter.sol#L485)

If the following actions after the approval fails, the allowance does not get reset

### Internal Pre-conditions

NA

### External Pre-conditions

NA

### Attack Path

1. User calls supply or repayBorrowInternal
2. Allowance is set via _approveToken
3. A revert occurs after approval from next operation (such as mint, repayBorrow, or a transfer failure) 
4. Allowance remains increased
5. User tries to call supply or repay again, but with a lower _amount 
6. Allowance stuck at high value
7. User is unable to proceed with new supply, repay, or liquidation operations 

### Impact

This issue blocks all flows that use _approveToken, including same-chain and cross-chain supply, repay, and liquidation.

### PoC

_No response_

### Mitigation

Approve should be placed inside the try/catch block or approval needs to be reset if the call fails.