Zesty Bamboo Lobster

High

# No Way To Refund Users If Operations Fail

### Summary

We have various operations throughout the protocol i.e

1. Supply.
2. Borrow
3. Redeem
4. Repay
5. Liquidate
6. ClaimLend  


But none of them has a mechanism to refund the users if the underlying operations (the Lerc20 operations) fail. 

For e.g this is a snippet of the [Supply](https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CoreRouter.sol#L61)

function of the CoreRouter::


```solidity

    function supply(uint256 _amount, address _token) external {
        address _lToken = lendStorage.underlyingTolToken(_token);

        require(_lToken != address(0), "Unsupported Token");

        require(_amount > 0, "Zero supply amount");

        // Transfer tokens from the user to the contract
        IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);

        _approveToken(_token, _lToken, _amount);

        // Get exchange rate before mint
        uint256 exchangeRateBefore = LTokenInterface(_lToken).exchangeRateStored();

        // Mint lTokens
        require(LErc20Interface(_lToken).mint(_amount) == 0, "Mint failed");

        // Calculate actual minted tokens using exchangeRate from before mint
        uint256 mintTokens = (_amount * 1e18) / exchangeRateBefore;

        lendStorage.addUserSuppliedAsset(msg.sender, _lToken);

        lendStorage.distributeSupplierLend(_lToken, msg.sender);

        // Update total investment using calculated mintTokens
        lendStorage.updateTotalInvestment(
            msg.sender, _lToken, lendStorage.totalInvestment(msg.sender, _lToken) + mintTokens
        );

        emit SupplySuccess(msg.sender, _lToken, _amount, mintTokens);
    }

```



We are transferring funds from the user to the protocol, after that we call the underlying mint function through the Lerc20 interface.


Which could fail due to multitude of reasons like the LendTroller pausing the mint operation for whatever reason.

If the operation fails there is way to catch the error/failure and the funds will be permanently stuck in the protocol without a way to recover the funds.


This leads to massive loss of funds for the users.

### Root Cause

- Lack of a fallback mechanism which repays users if the underlying operations fails

### Internal Pre-conditions

- LendTroller admin pauses the underlying operations.

### External Pre-conditions

- User need to call any of the functions like supply/borrow/redeem.

### Attack Path

- Not an attack , a regular logical failure.

### Impact

- Users could lose their funds permanently.
- Breaks user trust and their money.


### PoC

_No response_

### Mitigation

- Add a try/catch block around the underlying operation, if it fails refund the users through the catch block.