Lucky Felt Panther

Medium

# ETH Lockout Due to Missing Withdrawal Function in receive()

### Summary

The contract includes a `receive()` function, This function allows the contract to accept ETH sent directly to it (e.g., via .`transfer()` or .`send()`), but there is no corresponding mechanism to withdraw or recover that ETH.

As a result, any ETH sent to the contract (either accidentally or intentionally) becomes permanently locked within the contract.

### Root Cause

```solidity
receive() external payable {} // @audit-issue: no way to withdraw ETH sent directly to the contract
```

### Internal Pre-conditions

https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CoreRouter.sol#L46-L47

### External Pre-conditions

https://github.com/sherlock-audit/2025-05-lend-audit-contest/blob/main/Lend-V2/src/LayerZero/CoreRouter.sol#L46-L47

### Attack Path

ETH Loss from User Mistakes
Users or integrators might mistakenly send ETH directly to the contract address. Since the receive() function accepts it, the transaction won't revert â€” but that ETH will be stuck forever, with no way to retrieve it.

Example:
A user runs:

```solidity
payable(contractAddress).transfer(1 ether);
```

The contract receives the ETH, but the ETH balance becomes unrecoverable.



### Impact

* Funds can be lost forever (both user and protocol assets).

* Breaks user expectations if they assume all accepted funds can be recovered or used.

* Adds tech debt: locked ETH accumulates and cannot be reclaimed without a new contract deployment or forceful migration.

### PoC

_No response_

### Mitigation

```solidity
 function withdrawEth() external {
        uint256 balance = userBalances[msg.sender];
        require(balance > 0, "No ETH to withdraw");

        userBalances[msg.sender] = 0;

        (bool success, ) = msg.sender.call{value: balance}("");
        require(success, "ETH transfer failed");
    }
```